spring.config.import=optional:file:.env[.properties],optional:file:services/parking-lot-service/.env[.properties]
spring.application.name=parking-lot-service
server.port=${SERVER_PORT:8082}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.main.banner-mode=off
